version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${HTTP_PORT}:8080'
    env_file: .env.dev
    networks:
      - postgres_network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17.5-bookworm
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: [
        'CMD', 'pg_isready',
        '--username', '${POSTGRES_USERNAME}',
        '--dbname', '${POSTGRES_DATABASE}',
        '--port', '5432'
      ]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
